name: modern-pandas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.1
  - numpy=1.13.0
  - pandas=0.20.2
  - matplotlib=2.0.2
  - seaborn=0.7.1
  - ipython=6.1.0
  - jupyter=1.0.0
  - notebook=5.0.0
  - dask=0.15.0
  - distributed=1.17.1
  - toolz=0.8.2
  - pandas-datareader=0.4.0
  - scikit-learn=0.18.2
  - scipy=0.19.1
  - statsmodels=0.8.0
  - pytables==3.4.2
  - lxml==3.8.0
  - feather-format
  - rpy2
  - pip:
    - lifetimes==0.6.0.0
    - altair
